# Generated by Django 4.2.7 on 2024-03-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='images/default-user.avif', upload_to='avatar'),
        ),
    ]
