# Generated by Django 4.2.7 on 2024-03-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='background_image',
            field=models.ImageField(default='images/default-user.avif', upload_to='background_images/'),
        ),
    ]
