# Generated by Django 5.0.3 on 2024-07-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='images/default-user.jpg', upload_to='avatar'),
        ),
    ]
