# Generated by Django 5.0.3 on 2024-07-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'text'), ('file', 'file')], default='text', max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='background_image',
            field=models.ImageField(default='images/default-background.jpg', upload_to='background_images/'),
        ),
    ]
