# Generated by Django 5.0.3 on 2024-07-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_message_message_type_alter_user_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='message-files/'),
        ),
    ]
